export const browserCoreExamples = [
  "sendell browser status",
  "sendell browser start",
  "sendell browser stop",
  "sendell browser tabs",
  "sendell browser open https://example.com",
  "sendell browser focus abcd1234",
  "sendell browser close abcd1234",
  "sendell browser screenshot",
  "sendell browser screenshot --full-page",
  "sendell browser screenshot --ref 12",
  "sendell browser snapshot",
  "sendell browser snapshot --format aria --limit 200",
  "sendell browser snapshot --efficient",
  "sendell browser snapshot --labels",
];

export const browserActionExamples = [
  "sendell browser navigate https://example.com",
  "sendell browser resize 1280 720",
  "sendell browser click 12 --double",
  'sendell browser type 23 "hello" --submit',
  "sendell browser press Enter",
  "sendell browser hover 44",
  "sendell browser drag 10 11",
  "sendell browser select 9 OptionA OptionB",
  "sendell browser upload /tmp/file.pdf",
  'sendell browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "sendell browser dialog --accept",
  'sendell browser wait --text "Done"',
  "sendell browser evaluate --fn '(el) => el.textContent' --ref 7",
  "sendell browser console --level error",
  "sendell browser pdf",
];
